export const projects = [
  {
    title: "CoinsCave",
    description: "Kripto paraların güncel takip edilmesini sağlayan uygulama",
    image: "/images/1.png",
    tags: ["React", "Axios"],
    visit: "https://coins-cave-kripto-takip.vercel.app/",
    source: "https://github.com/Bariscncfc/CoinsCave-Kripto-Takip-",
    id: 0,
  },
  {
    title: "Recipedia",
    description: "Yemek tarifleri sunan uygulama",
    image: "/images/2.png",
    tags: ["React", "JavaScript"],
    visit: "https://recipedia-three.vercel.app/",
    source: "https://github.com/Bariscncfc/Recipedia",
    id: 1,
  },
  {
    title: "Netflix Klon",
    description: "netflix resmi web sayfasının klon uygulaması",
    image: "/images/3.png",
    tags: ["HTML", "CSS", "Javascript"],
    visit: "https://netflix-clone-website-sigma.vercel.app/",
    source: "https://github.com/Bariscncfc/Netflix-Landing-Page",
    id: 2,
  },
  {
    title: "Typing Game",
    description: "Klavyede ne kadar hızlı olduğunu test eden oyun uygulaması",
    image: "/images/4.png",
    tags: ["HTML", "CSS", "Javascript"],
    visit: "https://typing-game-zeta-three.vercel.app/",
    source: "https://github.com/Bariscncfc/Typing-Game",
    id: 3,
  },
];
